on:
  push:
    branches: [master]
    paths-ignore:
      - 'build_doc.sh'
      - 'check.sh'
      - 'run_ci_tests.sh'
      - 'start_sshd.sh'
      - 'stop_sshd.sh'
  pull_request:
    paths-ignore:
      - 'build_doc.sh'
      - 'check.sh'
      - 'run_ci_tests.sh'
      - 'start_sshd.sh'
      - 'stop_sshd.sh'
name: Minimum Supported Rust Version
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.56.1
          override: true
      - uses: actions/checkout@v2
      - name: cargo +1.56.1 check
        uses: actions-rs/cargo@v1
        with:
          command: check
