on:
  push:
    branches: [master]
  pull_request:
name: shellcheck
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        run: shellcheck *.sh
